### ISSUE TITLE
Unable to generate list. max matches value was reached

### ISSUE THREAD

**Issue by arodbits** [kaltura/KalturaGeneratedAPIClientsPHP53#3]
Why can't I list ALL the entries available in Kaltura? (using the listAction method).

When using the FilterPager with any pageIndex greater than 20 and the pageZise  equals to 500, an ApiException with the message "Unable to generate list. max matches value was reached" gets triggered. 

There're about other ~34,000 entries available but only 10,500 of those get resolved before the exception gets triggered. 

I'd appreciate any help with this. 
Thanks.

**Comment by kaltura-hooks** [comment]
Hi @anthony2727,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by kaltura-hooks** [comment]
Hi @anthony2727,
Thank you for contributing this pull request!
The KalturaGeneratedAPIClientsPHP53 is autogenerated from https://github.com/kaltura/server under generator/sources/__LANG__
Please create a new pull on the server repo.

**Comment by kaltura-hooks** [comment]
Hi @anthony2727,
Thank you for contributing this pull request!
The KalturaGeneratedAPIClientsPHP53 is autogenerated from https://github.com/kaltura/server under generator/sources/__LANG__
Please create a new pull on the server repo.

**Comment by kaltura-hooks** [comment]
Hi @anthony2727,
Thank you for contributing this pull request!
The KalturaGeneratedAPIClientsPHP53 is autogenerated from https://github.com/kaltura/server under generator/sources/__LANG__
Please create a new pull on the server repo.

**Comment by kaltura-hooks** [comment]
Hi @anthony2727,
Thank you for contributing this pull request!
The KalturaGeneratedAPIClientsPHP53 is autogenerated from https://github.com/kaltura/server under generator/sources/__LANG__
Please create a new pull on the server repo.

**Comment by kaltura-hooks** [comment]
Hi @anthony2727,
Thank you for contributing this pull request!
The KalturaGeneratedAPIClientsPHP53 is autogenerated from https://github.com/kaltura/server under generator/sources/__LANG__
Please create a new pull on the server repo.

**Comment by tan-tan-kanarek** [comment]
Kaltura search engine is limited to 10,000 results and therefore the pagination has the same limit.
To bypass the limitation, you can list your entries ordered by creation date and and after listing the first 10,000 you can add a condition to the filter to return only entries that their creation date is before (or after, depends on your ordering direction). This way you'll be listing also the next 10,000 entries and so on.

**Comment by jessp01** [comment]
Closing the issue. @anthony2727 - should you need more guidance about this, following the approach described by @tan-tan-kanarek above, please post at forum.kaltura.org.

Thanks,

**Comment by kenpeter** [comment]
@tan-tan-kanarek, 
`the media object has listAction(Filter, Pager). `

I have these settings
```
Pager.pageSize = 20;
Pager.pageIndex = 501;
```
The record num is 10020, which outbounds 10000 mark. It outputs
`Unable to generate list. max matches value was reached`

My question is that I am pulling small amount of records, why it still hit the mark.
Does it mean it always counting 10k mark in pager?

**Comment by tan-tan-kanarek** [comment]
The amount of entries you try to fetch is irrelevant to the way the backend works, you can't get even one entry if its location in the list is after 10,000.

**Comment by kenpeter** [comment]
@tan-tan-kanarek 
Are you able to have a look at this: https://forum.kaltura.org/t/how-to-get-all-media-entries-order-by-lastplayedat-in-php/8189

**Comment by kenpeter** [comment]
Hi,

```
$ks = $client->generateSession(
      KALTURA_ADMIN_SECRET,
      '',
      \KalturaSessionType::ADMIN,
      KALTURA_PARTNER_ID,
      86400,
      $sessionPrivileges
    );
```

I set sessionPrivileges = 'disableentitlement', I am able to get 50k records, which is a big improvement.
Is there any setting that I can get all entries? I need to get 90k records.

Ref: https://knowledge.kaltura.com/kalturas-api-authentication-and-security

**Comment by tan-tan-kanarek** [comment]
Since you're filtering by lastPlayedAtGreaterThanOrEqual and incrementing it in every request you should be able to list all your entries that ever played.
If you want to list all your entries, you can filter be create date instead.
