### ISSUE TITLE
Version that works with mp.streamamg.com

### ISSUE THREAD

**Issue by petergallagher** [kaltura/KalturaGeneratedAPIClientsPHP53#5]
Is there a version of this SDK that works with mp.streamamg.com or am I forced to manually include the library from that website instead of using composer?

**Comment by kaltura-hooks** [comment]
Hi @petergallagher,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello @petergallagher,

As noted here: http://mp.streamamg.com/start/index.php, the StreamUK platform is built on the Kaltura Open Source code base, which includes, among other components, the Kaltura Server.
Therefore, in principle, yes, the client lib from this repo [which is also used to generate the Composer package] should work. That said, it is very important to use a client of a version compatible with the one running on the StreamUK servers.
Note that we will not be providing support for using this against the StreamUK endpoint as their platform is not managed by us in any way.

**Comment by petergallagher** [comment]
Yeah, I realise now that it's a hosted version, although I would have expected that as they are both version 3 of the same API there would not have been breaking changes, but as this doesn't seem to be the case I will just stick to using the older version of the client.
